version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
    depends_on:
      - postgres
    build:
      context: .
      target: builder
    command: sh -c -f "yarn mikro-orm schema:update --run&&yarn mikro-orm seeder:run --class=ConfigSeeder;yarn run start:prod"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - $PORT:$PORT
    networks:
      - postgres
    stdin_open: true
    tty: true
  