version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=ssqwec
      - MYSQL_DATABASE=husky
    volumes:
      - db:/var/lib/mysql
    ports:
    - 3307:3306
  app:
    depends_on:
      - mysqldb
    container_name: husadmin
    build:
      context: .
      target: builder
    command: sh -c -f "yarn mikro-orm schema:update --run&&yarn mikro-orm seeder:run --class=ConfigSeeder;yarn run start:prod"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
volumes: 
  db: